---
dune:git  clang:
  image: duneci/dune:git
  script: duneci-standard-test --opts=/duneci/opts.clang
  tags: [duneci]

dune:git  gcc:
  image: duneci/dune:git
  script: duneci-standard-test
  tags: [duneci]

dune:2.6  gcc:
  image: duneci/dune:2.6
  script: duneci-standard-test
  tags: [duneci]
